import React, { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "sq" | "en";

// ── All translations ────────────────────────────────────────────────────────
export const translations = {
  // ── Nav ──
  nav_dashboard: { sq: "Dashboard", en: "Dashboard" },
  nav_leads: { sq: "Leads", en: "Leads" },
  nav_clients: { sq: "Klientët", en: "Clients" },
  nav_invoices: { sq: "Invoices", en: "Invoices" },
  nav_bills: { sq: "Faturat Tona", en: "Our Bills" },
  nav_tasks: { sq: "Tasks", en: "Tasks" },
  nav_products: { sq: "Produkte", en: "Products" },
  nav_emails: { sq: "Emailet", en: "Emails" },
  nav_settings: { sq: "Settings", en: "Settings" },
  nav_logout: { sq: "Dilni (Logout)", en: "Logout" },
  nav_search: { sq: "Kërko...", en: "Search..." },

  // ── Common ──
  save: { sq: "Ruaj", en: "Save" },
  cancel: { sq: "Anulo", en: "Cancel" },
  delete: { sq: "Fshi", en: "Delete" },
  edit: { sq: "Redakto", en: "Edit" },
  add: { sq: "Shto", en: "Add" },
  create: { sq: "Krijo", en: "Create" },
  update: { sq: "Përditëso", en: "Update" },
  saving: { sq: "Duke ruajtur...", en: "Saving..." },
  loading: { sq: "Duke ngarkuar...", en: "Loading..." },
  search: { sq: "Kërko", en: "Search" },
  all: { sq: "Të gjitha", en: "All" },
  all_m: { sq: "Të gjithë", en: "All" },
  none: { sq: "Asnjë", en: "None" },
  notes: { sq: "Shënime", en: "Notes" },
  status: { sq: "Statusi", en: "Status" },
  name: { sq: "Emri", en: "Name" },
  email: { sq: "Email", en: "Email" },
  phone: { sq: "Telefon", en: "Phone" },
  company: { sq: "Kompania", en: "Company" },
  source: { sq: "Burimi", en: "Source" },
  date: { sq: "Data", en: "Date" },
  amount: { sq: "Shuma", en: "Amount" },
  description: { sq: "Përshkrim", en: "Description" },
  title: { sq: "Titulli", en: "Title" },
  client: { sq: "Klienti", en: "Client" },
  optional: { sq: "opsional", en: "optional" },
  error_required: { sq: "Gabim gjatë ruajtjes.", en: "Error saving." },
  error_delete: { sq: "Gabim gjatë fshirjes.", en: "Error deleting." },
  error_save: { sq: "Gabim gjatë ruajtjes.", en: "Error saving." },
  view_all: { sq: "Të gjitha", en: "View all" },
  total: { sq: "total", en: "total" },
  active: { sq: "Aktiv", en: "Active" },
  inactive: { sq: "Joaktiv", en: "Inactive" },
  saved_ok: { sq: "U ruajt!", en: "Saved!" },

  // ── Dashboard ──
  dash_welcome: { sq: "Mirëserdhët në CRM-in tuaj", en: "Welcome to your CRM" },
  dash_subtitle: { sq: "Menaxhoni leads, klientët, faturat, takimet dhe detyrat tuaja.", en: "Manage your leads, clients, invoices, appointments and tasks." },
  dash_leads_active: { sq: "Leads Aktive", en: "Active Leads" },
  dash_clients_total: { sq: "Klientë Total", en: "Total Clients" },
  dash_invoices_pending: { sq: "Fatura në Pritje", en: "Pending Invoices" },
  dash_appts_upcoming: { sq: "Takime të Ardhshme", en: "Upcoming Appointments" },
  dash_tasks_open: { sq: "Detyra të Hapura", en: "Open Tasks" },
  dash_appts_planned: { sq: "takime të planifikuara", en: "scheduled appointments" },
  dash_overdue: { sq: "të vonuara", en: "overdue" },
  dash_collected: { sq: "arkëtuar", en: "collected" },
  dash_high_priority: { sq: "prioritet i lartë", en: "high priority" },
  dash_active: { sq: "aktiv", en: "active" },
  dash_recent_clients: { sq: "Klientët e Fundit", en: "Recent Clients" },
  dash_recent_invoices: { sq: "Faturat e Fundit", en: "Recent Invoices" },
  dash_upcoming_appts: { sq: "Takimet e Ardhshme", en: "Upcoming Appointments" },
  dash_open_tasks: { sq: "Detyrat e Hapura", en: "Open Tasks" },
  dash_overdue_alert: { sq: "Keni", en: "You have" },
  dash_overdue_alert2: { sq: "faturë/a të vonuara.", en: "overdue invoice(s)." },
  dash_view_invoices: { sq: "Shiko faturat", en: "View invoices" },
  dash_no_clients: { sq: "Nuk ka klientë ende.", en: "No clients yet." },
  dash_no_invoices: { sq: "Nuk ka fatura ende.", en: "No invoices yet." },
  dash_no_appts: { sq: "Asnjë takim i planifikuar.", en: "No appointments scheduled." },
  dash_no_tasks: { sq: "Të gjitha detyrat janë kryer! 🎉", en: "All tasks are done! 🎉" },
  dash_due: { sq: "Skadence:", en: "Due:" },
  dash_deadline: { sq: "Afati:", en: "Deadline:" },
  dash_total_leads: { sq: "total leads", en: "total leads" },

  // ── Login ──
  login_title: { sq: "Sistemi i menaxhimit të klientëve", en: "Client management system" },
  login_username: { sq: "Emri i përdoruesit", en: "Username" },
  login_password: { sq: "Fjalëkalimi", en: "Password" },
  login_forgot: { sq: "Harruat fjalëkalimin?", en: "Forgot password?" },
  login_submit: { sq: "Kyçu", en: "Log in" },
  login_loading: { sq: "Duke u kyçur...", en: "Logging in..." },
  login_error: { sq: "Emri i përdoruesit ose fjalëkalimi është i gabuar.", en: "Wrong username or password." },
  login_secure: { sq: "Platform i sigurt · Të dhënat tuaja janë të mbrojtura", en: "Secure platform · Your data is protected" },
  login_footer: { sq: "Për bizneset tuaja", en: "For your business" },
  login_creds_title: { sq: "Kredencialet e hyrjes", en: "Login credentials" },
  login_creds_current: { sq: "Kredencialet aktuale", en: "Current credentials" },
  login_creds_user: { sq: "Emri i përdoruesit:", en: "Username:" },
  login_creds_pw: { sq: "Fjalëkalimi:", en: "Password:" },
  login_creds_change: { sq: "Mund ta ndryshoni fjalëkalimin pasi të kyçeni, nga", en: "You can change the password after logging in, from" },
  login_creds_settings: { sq: "Settings → Llogaria", en: "Settings → Account" },
  login_ok: { sq: "Mirë, e kuptova", en: "Got it" },

  // ── Leads ──
  leads_title: { sq: "Leads & Takimet", en: "Leads & Appointments" },
  leads_add: { sq: "Shto Lead", en: "Add Lead" },
  leads_appt_new: { sq: "Takim i Ri", en: "New Appointment" },
  leads_tab_leads: { sq: "Leads", en: "Leads" },
  leads_tab_appts: { sq: "Takimet", en: "Appointments" },
  leads_conversion: { sq: "konvertim", en: "conversion" },
  leads_search: { sq: "Kërko leads...", en: "Search leads..." },
  leads_drag_here: { sq: "Tërhiq një lead këtu", en: "Drag a lead here" },
  leads_drag: { sq: "Tërhiq", en: "Drag" },
  leads_source: { sq: "Burimi:", en: "Source:" },
  leads_stage_new: { sq: "I Ri", en: "New" },
  leads_stage_contacted: { sq: "Kontaktuar", en: "Contacted" },
  leads_stage_negotiation: { sq: "Negocim", en: "Negotiation" },
  leads_stage_converted: { sq: "Konvertuar", en: "Converted" },
  leads_add_title: { sq: "Shto Lead të Ri", en: "Add New Lead" },
  leads_edit_title: { sq: "Redakto Lead-in", en: "Edit Lead" },
  leads_name: { sq: "Emri *", en: "Name *" },
  leads_email: { sq: "Email *", en: "Email *" },
  leads_phone: { sq: "Telefon", en: "Phone" },
  leads_company: { sq: "Kompania", en: "Company" },
  leads_source_label: { sq: "Burimi", en: "Source" },
  leads_stage_label: { sq: "Stadi", en: "Stage" },
  leads_notes_label: { sq: "Shënime", en: "Notes" },
  leads_source_select: { sq: "— Zgjidh burimin —", en: "— Select source —" },
  leads_saved: { sq: "Lead-i u përditësua!", en: "Lead updated!" },
  leads_added: { sq: "Lead-i u shtua!", en: "Lead added!" },
  leads_deleted: { sq: "u fshi.", en: "was deleted." },
  leads_moved: { sq: "u zhvendos te", en: "moved to" },
  leads_required: { sq: "Emri dhe email-i janë të detyrueshëm.", en: "Name and email are required." },

  // ── Appointments (inside Leads) ──
  appt_upcoming: { sq: "Të ardhshme", en: "Upcoming" },
  appt_past: { sq: "Të kaluara", en: "Past" },
  appt_all: { sq: "Të gjitha", en: "All" },
  appt_none: { sq: "Asnjë takim", en: "No appointments" },
  appt_none_upcoming: { sq: "Nuk keni takime të planifikuara.", en: "No appointments scheduled." },
  appt_none_past: { sq: "Nuk ka takime të kaluara.", en: "No past appointments." },
  appt_client: { sq: "Klienti *", en: "Client *" },
  appt_title: { sq: "Titulli *", en: "Title *" },
  appt_datetime: { sq: "Data dhe Ora *", en: "Date & Time *" },
  appt_notes: { sq: "Shënime", en: "Notes" },
  appt_client_select: { sq: "Zgjidh klientin...", en: "Select client..." },
  appt_title_placeholder: { sq: "p.sh. Konsultë fillestare", en: "e.g. Initial consultation" },
  appt_unknown_client: { sq: "Klient i panjohur", en: "Unknown client" },
  appt_saved: { sq: "Takimi u përditësua!", en: "Appointment updated!" },
  appt_created: { sq: "Takimi u krijua!", en: "Appointment created!" },
  appt_required: { sq: "Plotëso klientin, titullin dhe datën.", en: "Fill in client, title and date." },
  appt_edit_title: { sq: "Redakto Takimin", en: "Edit Appointment" },
  appt_new_title: { sq: "Takim i Ri", en: "New Appointment" },
  appt_create_btn: { sq: "Krijo", en: "Create" },

  // ── Clients ──
  clients_title: { sq: "Klientët", en: "Clients" },
  clients_add: { sq: "Shto Klient", en: "Add Client" },
  clients_search: { sq: "Kërko klientë...", en: "Search clients..." },
  clients_col_client: { sq: "Klienti", en: "Client" },
  clients_col_email: { sq: "Email / Tel", en: "Email / Phone" },
  clients_col_industry: { sq: "Industria", en: "Industry" },
  clients_col_contract: { sq: "Vlera Kontratës", en: "Contract Value" },
  clients_col_city: { sq: "Qyteti", en: "City" },
  clients_col_status: { sq: "Statusi", en: "Status" },
  clients_col_actions: { sq: "Veprime", en: "Actions" },
  clients_none: { sq: "Asnjë klient", en: "No clients" },
  clients_none_filter: { sq: "Nuk u gjet asnjë klient me këto filtra.", en: "No clients match these filters." },
  clients_none_empty: { sq: "Shtoni klientin e parë për të filluar.", en: "Add your first client to get started." },
  clients_add_title: { sq: "Shto Klient të Ri", en: "Add New Client" },
  clients_edit_title: { sq: "Redakto Klientin", en: "Edit Client" },
  clients_name: { sq: "Emri *", en: "Name *" },
  clients_email: { sq: "Email *", en: "Email *" },
  clients_phone: { sq: "Telefoni", en: "Phone" },
  clients_nipt: { sq: "NIPT", en: "Tax ID (NIPT)" },
  clients_address: { sq: "Adresa", en: "Address" },
  clients_city: { sq: "Qyteti", en: "City" },
  clients_country: { sq: "Shteti", en: "Country" },
  clients_website: { sq: "Faqja Web", en: "Website" },
  clients_contact_person: { sq: "Personi Kontaktit", en: "Contact Person" },
  clients_industry: { sq: "Industria / Sektori", en: "Industry / Sector" },
  clients_contract_value: { sq: "Vlera Kontratës", en: "Contract Value" },
  clients_notes: { sq: "Shënime", en: "Notes" },
  clients_status: { sq: "Statusi", en: "Status" },
  clients_saved: { sq: "Klienti u përditësua!", en: "Client updated!" },
  clients_added: { sq: "Klienti u shtua!", en: "Client added!" },
  clients_required: { sq: "Emri dhe email-i janë të detyrueshëm.", en: "Name and email are required." },
  clients_send_email: { sq: "Dërgo Email", en: "Send Email" },
  status_lead: { sq: "Lead", en: "Lead" },
  status_active: { sq: "Aktiv", en: "Active" },
  status_inactive: { sq: "Joaktiv", en: "Inactive" },

  // ── Invoices ──
  invoices_title: { sq: "Faturat", en: "Invoices" },
  invoices_create: { sq: "Krijo Faturë", en: "Create Invoice" },
  invoices_search: { sq: "Kërko fatura...", en: "Search invoices..." },
  invoices_col_nr: { sq: "Nr. Faturës", en: "Invoice #" },
  invoices_col_client: { sq: "Klienti", en: "Client" },
  invoices_col_amount: { sq: "Shuma", en: "Amount" },
  invoices_col_due: { sq: "Skadenca", en: "Due Date" },
  invoices_col_status: { sq: "Statusi", en: "Status" },
  invoices_none: { sq: "Asnjë faturë", en: "No invoices" },
  invoices_none_filter: { sq: "Nuk u gjet asnjë faturë me këto filtra.", en: "No invoices match these filters." },
  invoices_none_empty: { sq: "Krijoni faturën e parë.", en: "Create your first invoice." },
  invoices_add_title: { sq: "Faturë e Re", en: "New Invoice" },
  invoices_edit_title: { sq: "Redakto Faturën", en: "Edit Invoice" },
  invoices_client: { sq: "Klienti *", en: "Client *" },
  invoices_nr: { sq: "Nr. Faturës *", en: "Invoice # *" },
  invoices_lines: { sq: "Zërat (nga produktet)", en: "Line items (from products)" },
  invoices_add_line: { sq: "+ Shto zë", en: "+ Add line" },
  invoices_no_lines: { sq: "Nuk ka zëra — shuma do të vendoset manualisht.", en: "No lines — amount will be set manually." },
  invoices_currency: { sq: "Monedha", en: "Currency" },
  invoices_amount: { sq: "Shuma", en: "Amount" },
  invoices_due_date: { sq: "Data e Skadencës *", en: "Due Date *" },
  invoices_status: { sq: "Statusi", en: "Status" },
  invoices_total: { sq: "Totali:", en: "Total:" },
  invoices_mark_paid: { sq: "Shëno si paguar", en: "Mark as paid" },
  invoices_paid: { sq: "Fatura u shënua si e paguar!", en: "Invoice marked as paid!" },
  invoices_saved: { sq: "Fatura u përditësua!", en: "Invoice updated!" },
  invoices_created: { sq: "Fatura u krijua!", en: "Invoice created!" },
  invoices_required: { sq: "Plotëso të gjitha fushat e detyrueshme.", en: "Fill in all required fields." },
  invoices_status_paid: { sq: "Paguar", en: "Paid" },
  invoices_status_pending: { sq: "Në pritje", en: "Pending" },
  invoices_status_overdue: { sq: "Vonuar", en: "Overdue" },

  // ── Bills ──
  bills_title: { sq: "Faturat për të Paguar", en: "Bills to Pay" },
  bills_subtitle: { sq: "faturë/a të furnitorëve", en: "supplier bill(s)" },
  bills_add: { sq: "Shto Faturë", en: "Add Bill" },
  bills_search: { sq: "Kërko fatura...", en: "Search bills..." },
  bills_col_supplier: { sq: "Furnitori", en: "Supplier" },
  bills_col_nr: { sq: "Nr. Faturës", en: "Bill #" },
  bills_col_category: { sq: "Kategoria", en: "Category" },
  bills_col_amount: { sq: "Shuma", en: "Amount" },
  bills_col_due: { sq: "Skadenca", en: "Due Date" },
  bills_col_status: { sq: "Statusi", en: "Status" },
  bills_due_soon: { sq: "faturë skadon brenda 7 ditëve — kujdes!", en: "bill(s) due within 7 days — attention!" },
  bills_paid: { sq: "Të paguara", en: "Paid" },
  bills_pending: { sq: "Në pritje", en: "Pending" },
  bills_overdue: { sq: "Vonuar", en: "Overdue" },
  bills_unpaid_total: { sq: "Totali i papaguar", en: "Total unpaid" },
  bills_none: { sq: "Asnjë faturë", en: "No bills" },
  bills_none_filter: { sq: "Nuk u gjet asnjë faturë me këto filtra.", en: "No bills match these filters." },
  bills_none_empty: { sq: "Shto faturën e parë të furnitorit.", en: "Add your first supplier bill." },
  bills_add_title: { sq: "Faturë e Re", en: "New Bill" },
  bills_edit_title: { sq: "Redakto Faturën", en: "Edit Bill" },
  bills_supplier: { sq: "Furnitori *", en: "Supplier *" },
  bills_nr: { sq: "Nr. Faturës *", en: "Bill # *" },
  bills_description: { sq: "Përshkrim", en: "Description" },
  bills_amount: { sq: "Shuma *", en: "Amount *" },
  bills_category: { sq: "Kategoria", en: "Category" },
  bills_issue_date: { sq: "Data e Lëshimit", en: "Issue Date" },
  bills_due_date: { sq: "Data e Skadencës *", en: "Due Date *" },
  bills_status: { sq: "Statusi", en: "Status" },
  bills_notes: { sq: "Shënime", en: "Notes" },
  bills_mark_paid: { sq: "Shëno si paguar", en: "Mark as paid" },
  bills_marked_paid: { sq: "Fatura u shënua si e paguar!", en: "Bill marked as paid!" },
  bills_saved: { sq: "Fatura u përditësua!", en: "Bill updated!" },
  bills_created: { sq: "Fatura u krijua!", en: "Bill created!" },
  bills_required: { sq: "Plotëso të gjitha fushat e detyrueshme.", en: "Fill in all required fields." },
  bills_today: { sq: "Sot!", en: "Today!" },
  bills_days_delay: { sq: "ditë vonesë", en: "days overdue" },
  bills_days: { sq: "ditë", en: "days" },
  bills_all_categories: { sq: "Të gjitha kategoritë", en: "All categories" },
  bills_select_cat: { sq: "Zgjidh...", en: "Select..." },

  // ── Tasks ──
  tasks_title: { sq: "Detyrat", en: "Tasks" },
  tasks_open: { sq: "të hapura", en: "open" },
  tasks_done_count: { sq: "të kryera", en: "completed" },
  tasks_new: { sq: "Detyrë e Re", en: "New Task" },
  tasks_col_todo: { sq: "Të bëra", en: "To Do" },
  tasks_col_inprogress: { sq: "Në progres", en: "In Progress" },
  tasks_col_done: { sq: "Të kryera", en: "Done" },
  tasks_drag_here: { sq: "Zvarrit këtu", en: "Drop here" },
  tasks_add_in_col: { sq: "Shto detyrë", en: "Add task" },
  tasks_priority_high: { sq: "E lartë", en: "High" },
  tasks_priority_medium: { sq: "Mesatare", en: "Medium" },
  tasks_priority_low: { sq: "E ulët", en: "Low" },
  tasks_edit_title: { sq: "Redakto Detyrën", en: "Edit Task" },
  tasks_new_title: { sq: "Detyrë e Re", en: "New Task" },
  tasks_title_label: { sq: "Titulli *", en: "Title *" },
  tasks_desc_label: { sq: "Përshkrimi", en: "Description" },
  tasks_col_label: { sq: "Kolona", en: "Column" },
  tasks_due_label: { sq: "Afati", en: "Deadline" },
  tasks_priority_label: { sq: "Prioriteti", en: "Priority" },
  tasks_title_placeholder: { sq: "Çfarë duhet bërë?", en: "What needs to be done?" },
  tasks_desc_placeholder: { sq: "Detaje shtesë (opsionale)...", en: "Additional details (optional)..." },
  tasks_saved: { sq: "Detyra u përditësua!", en: "Task updated!" },
  tasks_added: { sq: "Detyra u shtua!", en: "Task added!" },
  tasks_required: { sq: "Titulli është i detyrueshëm.", en: "Title is required." },
  tasks_no_description: { sq: "Nuk ka përshkrim.", en: "No description." },
  tasks_priority_meta: { sq: "Prioriteti", en: "Priority" },
  tasks_due_meta: { sq: "Afati", en: "Deadline" },
  tasks_not_due: { sq: "Pa afat", en: "No deadline" },
  tasks_column_meta: { sq: "Kolona", en: "Column" },
  tasks_created_meta: { sq: "Krijuar", en: "Created" },
  tasks_delete: { sq: "Fshi", en: "Delete" },
  tasks_edit: { sq: "Redakto", en: "Edit" },
  tasks_preview: { sq: "Shiko detajet", en: "View details" },
  tasks_desc_section: { sq: "Përshkrimi", en: "Description" },

  // ── Products ──
  products_title: { sq: "Produkte & Shërbime", en: "Products & Services" },
  products_add: { sq: "Shto", en: "Add" },
  products_search: { sq: "Kërko...", en: "Search..." },
  products_col_name: { sq: "Emri", en: "Name" },
  products_col_type: { sq: "Lloji", en: "Type" },
  products_col_price: { sq: "Çmimi", en: "Price" },
  products_col_unit: { sq: "Njësia", en: "Unit" },
  products_col_status: { sq: "Statusi", en: "Status" },
  products_active: { sq: "Aktive", en: "Active" },
  products_type_product: { sq: "Produkt", en: "Product" },
  products_type_service: { sq: "Shërbim", en: "Service" },
  products_none: { sq: "Asnjë produkt", en: "No products" },
  products_none_filter: { sq: "Nuk u gjet asnjë rekord me këto filtra.", en: "No records match these filters." },
  products_none_empty: { sq: "Shtoni produktin ose shërbimin e parë.", en: "Add your first product or service." },
  products_add_title: { sq: "Shto Produkt / Shërbim", en: "Add Product / Service" },
  products_edit_title: { sq: "Redakto", en: "Edit" },
  products_type_label: { sq: "Lloji *", en: "Type *" },
  products_name_label: { sq: "Emri *", en: "Name *" },
  products_desc_label: { sq: "Përshkrim (opsional)", en: "Description (optional)" },
  products_currency: { sq: "Monedha", en: "Currency" },
  products_price_label: { sq: "Çmimi", en: "Price" },
  products_unit_label: { sq: "Njësia", en: "Unit" },
  products_saved: { sq: "Produkti u përditësua!", en: "Product updated!" },
  products_added: { sq: "Produkti u shtua!", en: "Product added!" },
  products_name_required: { sq: "Emri është i detyrueshëm.", en: "Name is required." },
  products_price_required: { sq: "Çmimi duhet të jetë një numër valid (0 ose më shumë).", en: "Price must be a valid number (0 or more)." },
  products_active_label: { sq: "Aktiv", en: "Active" },
  products_inactive_label: { sq: "Joaktiv", en: "Inactive" },
  products_records: { sq: "rekord/e", en: "record(s)" },

  // ── Emails ──
  emails_title: { sq: "Emailet", en: "Emails" },
  emails_sent_count: { sq: "email të dërguar", en: "email(s) sent" },
  emails_compose: { sq: "Kompozo Email", en: "Compose Email" },
  emails_search: { sq: "Kërko emaile...", en: "Search emails..." },
  emails_all_clients: { sq: "Të gjithë klientët", en: "All clients" },
  emails_none: { sq: "Asnjë email", en: "No emails" },
  emails_none_filter: { sq: "Nuk u gjet asnjë email me këto filtra.", en: "No emails match these filters." },
  emails_none_empty: { sq: "Dërgoni emailin e parë tek një klient.", en: "Send your first email to a client." },
  emails_sent_badge: { sq: "Dërguar", en: "Sent" },
  emails_reply: { sq: "Përgjigju", en: "Reply" },
  emails_new_email: { sq: "Email i Ri", en: "New Email" },
  emails_to: { sq: "Tek:", en: "To:" },
  emails_email_label: { sq: "Email:", en: "Email:" },
  emails_template: { sq: "Zgjidh template-in:", en: "Choose template:" },
  emails_subject: { sq: "Temë:", en: "Subject:" },
  emails_body_placeholder: { sq: "Shkruaj mesazhin...", en: "Write your message..." },
  emails_send: { sq: "Dërgo", en: "Send" },
  emails_sending: { sq: "Duke dërguar...", en: "Sending..." },
  emails_sent_ok: { sq: "Email-i u dërgua me sukses!", en: "Email sent successfully!" },
  emails_mailto_info: { sq: "Hapet klienti juaj i emailit — klikoni Dërgo aty.", en: "Your email client will open — click Send there." },
  emails_required: { sq: "Plotëso të gjitha fushat e detyrueshme.", en: "Fill in all required fields." },
  emails_select_client: { sq: "Zgjidh klientin...", en: "Select client..." },
  emails_subject_placeholder: { sq: "Subjekti i emailit...", en: "Email subject..." },
  emails_to_all: { sq: "Tek:", en: "To:" },
  emails_close: { sq: "Mbyll", en: "Close" },
  emails_from: { sq: "Nga emaili i", en: "From email on" },

  // ── Settings ──
  settings_title: { sq: "Cilësimet", en: "Settings" },
  settings_subtitle: { sq: "Menaxhoni kompaninë, ekipin dhe integrimet", en: "Manage your company, team and integrations" },
  settings_tab_company: { sq: "Kompania", en: "Company" },
  settings_tab_team: { sq: "Ekipi", en: "Team" },
  settings_tab_integrations: { sq: "Integrime", en: "Integrations" },
  settings_tab_jobboard: { sq: "Tabela e Punëve", en: "Job Board" },
  settings_tab_account: { sq: "Llogaria", en: "Account" },
  settings_company_title: { sq: "Informacioni i Kompanisë", en: "Company Information" },
  settings_company_name: { sq: "Emri i Kompanisë", en: "Company Name" },
  settings_website: { sq: "Faqja Web", en: "Website" },
  settings_hr_email: { sq: "Email HR", en: "HR Email" },
  settings_currency: { sq: "Monedha", en: "Currency" },
  settings_notifications: { sq: "Njoftime", en: "Notifications" },
  settings_save: { sq: "Ruaj Ndryshimet", en: "Save Changes" },
  settings_team_title: { sq: "Anëtarët e Ekipit", en: "Team Members" },
  settings_invite: { sq: "Fto Anëtar", en: "Invite Member" },
  settings_integrations_title: { sq: "Integrime", en: "Integrations" },
  settings_connect: { sq: "Lidh", en: "Connect" },
  settings_disconnect: { sq: "Shkëput", en: "Disconnect" },
  settings_jobboard_title: { sq: "Cilësimet e Tabelës", en: "Job Board Settings" },
  settings_jobboard_url: { sq: "URL Publike", en: "Public URL" },
  settings_copy: { sq: "Kopjo", en: "Copy" },
  settings_account_title: { sq: "Ndrysho Fjalëkalimin", en: "Change Password" },
  settings_current_pw: { sq: "Fjalëkalimi aktual", en: "Current password" },
  settings_new_pw: { sq: "Fjalëkalimi i ri", en: "New password" },
  settings_confirm_pw: { sq: "Konfirmo fjalëkalimin e ri", en: "Confirm new password" },
  settings_change_pw: { sq: "Ndrysho Fjalëkalimin", en: "Change Password" },
  settings_pw_changed: { sq: "Fjalëkalimi u ndryshua me sukses!", en: "Password changed successfully!" },
  settings_pw_wrong: { sq: "Fjalëkalimi aktual është i gabuar.", en: "Current password is incorrect." },
  settings_pw_short: { sq: "Fjalëkalimi i ri duhet të ketë të paktën 6 karaktere.", en: "New password must be at least 6 characters." },
  settings_pw_mismatch: { sq: "Fjalëkalimet e reja nuk përputhen.", en: "New passwords do not match." },
  settings_user: { sq: "Përdoruesi:", en: "User:" },
  settings_pw_min: { sq: "Minimum 6 karaktere", en: "Minimum 6 characters" },
  settings_pw_repeat: { sq: "Përsërit fjalëkalimin e ri", en: "Repeat new password" },
} as const;

type TranslationKey = keyof typeof translations;

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LangContext = createContext<LangContextType | null>(null);

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(
    () => (localStorage.getItem("crmLang") as Lang) || "sq"
  );

  const setLang = (l: Lang) => {
    localStorage.setItem("crmLang", l);
    setLangState(l);
  };

  const t = (key: TranslationKey): string => translations[key][lang];

  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error("useLang must be used within LangProvider");
  return ctx;
}
